//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PyPup.ServiceBus.Deployment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TraceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TraceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PyPup.ServiceBus.Deployment.TraceMessages", typeof(TraceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating queue &quot;{0}&quot;.
        /// </summary>
        internal static string CreatingQueue {
            get {
                return ResourceManager.GetString("CreatingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating subscription &quot;{1}&quot; to topic &quot;{0}&quot;.
        /// </summary>
        internal static string CreatingSubscription {
            get {
                return ResourceManager.GetString("CreatingSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating topic &quot;{0}&quot;.
        /// </summary>
        internal static string CreatingTopic {
            get {
                return ResourceManager.GetString("CreatingTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting queue &quot;{0}&quot;.
        /// </summary>
        internal static string DeletingQueue {
            get {
                return ResourceManager.GetString("DeletingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting subscription &quot;{1}&quot; to topic &quot;{0}&quot;.
        /// </summary>
        internal static string DeletingSubscription {
            get {
                return ResourceManager.GetString("DeletingSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting topic &quot;{0}&quot;.
        /// </summary>
        internal static string DeletingTopic {
            get {
                return ResourceManager.GetString("DeletingTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating existing queue &quot;{0}&quot;.
        /// </summary>
        internal static string UpdatingQueue {
            get {
                return ResourceManager.GetString("UpdatingQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating existing subsription &quot;{1}&quot; to topic &quot;{0}&quot;.
        /// </summary>
        internal static string UpdatingSubscription {
            get {
                return ResourceManager.GetString("UpdatingSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating existing topic &quot;{0}&quot;.
        /// </summary>
        internal static string UpdatingTopic {
            get {
                return ResourceManager.GetString("UpdatingTopic", resourceCulture);
            }
        }
    }
}
